# containerd
cni_bin_dir: /opt/cni/bin
cni_etc_dir: /etc/cni/net.d

# system paths
profile_dir: /etc/profile.d
systemd_service_dir: /usr/lib/systemd/system

# container-runtime paths
docker_etc_dir: /etc/docker
docker_data_dir: /var/lib/docker
containerd_etc_dir: /etc/containerd
containerd_data_dir: /var/lib/containerd

# etcd paths
# 为了提高性能，一般使用 SSD 或者和 data-dir 和 wal-dir 不同的磁盘；
etcd_data_dir: /var/lib/etcd
etcd_wal_dir: /var/lib/wal
etcd_config_dir: /etc/etcd
# 配置etcd持久化数据目录
# 0 3 * * * etcd_cron.sh -c 4 -d /data_bak/etcd &>/dev/null 2>&1
etcd_data_bak_dir: /data_bak/etcd

# kubernetes paths
kubernetes_etc_dir: /etc/kubernetes
lb_config_dir: "{{ kubernetes_etc_dir }}/lb-config"
kubernetes_log_dir: /var/log/kubernetes
kubelet_data_dir: /var/lib/kubelet
kube_proxy_data_dir: /var/lib/kube-proxy
manifest_dir: "{{ kubernetes_etc_dir }}/manifests"

# cert paths
k8s_pki_dir: "{{ kubernetes_etc_dir }}/pki"
etcd_pki_dir: "{{ k8s_pki_dir }}/etcd"

# cluster ha dir
haproxy_etc_dir: /etc/haproxy
keepalived_etc_dir: /etc/keepalived
